import { Button, VerticalBox } from "std-widgets.slint";
import { HorizontalBox, TextEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    in-out property<image> qrnote: @image-url("icons/QRNote.png");
    out property<string> thetext: "Pouet";
    callback request-increase-value();
    callback compute-qr-code();
    callback qr-note-edited();
    VerticalBox {
        TextEdit {
            text: thetext;
            width: 300px;
            height: 300px;
            edited(text) => {
                thetext = text;
                root.qr-note-edited();
            }
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
        Button {
            text: "Gen QRNote";
            clicked => {
                root.compute-qr-code();
            }
        }
        Image {
            source : qrnote;
            width: 100px;
            height: 100px;
        }
    }
}
