import { Button, VerticalBox } from "std-widgets.slint";
import { HorizontalBox, TextEdit, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<image> qrnote: @image-url("icons/QRNote.png");
    out property<string> thetext: "";
    in property<string> errormsg: "Ok";
    callback text-is-edited();
    VerticalBox {
        TextEdit {
            text: thetext;
            width: 300px;
            height: 300px;
            edited(text) => {
                thetext = text;
                root.text-is-edited();
            }
        }
        Image {
            source : qrnote;
            width: 150px;
            height: 150px;
        }
        LineEdit {
            text: errormsg;
            width: 300px;
            read-only: true;
            horizontal-alignment: center;
        }
    }
}
