import { Button, VerticalBox } from "std-widgets.slint";
import { HorizontalBox, TextEdit, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "QRNote";
    icon: @image-url("icons/QRNote.png");
    in-out property<image> qrnote: @image-url("icons/QRNote.png");
    out property<string> thetext: "";
    in property<string> errormsg: "";
    in property<int> charcount: 0;
    in property<int> qr_size: 150;
    callback text-is-edited();
    VerticalBox {
        TextEdit {
            text: thetext;
            preferred-width: 300px;
            preferred-height: 300px;
            edited(text) => {
                thetext = text;
                root.text-is-edited();
            }
        }
        LineEdit {
            text: charcount;
            preferred-width: 300px;
            read-only: true;
            horizontal-alignment: center;
        }
        Image {
            source : qrnote;
            preferred-width: qr_size*1px;
            preferred-height:qr_size*1px;
        }
        LineEdit {
            text: errormsg;
            preferred-width: 300px;
            read-only: true;
            horizontal-alignment: center;
        }
    }
}
